allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-unwrap-in-tests = true
doc-valid-idents = ["GGUF", "LFM2", "LFM2.5", "Q8_0", "SwiGLU", "SiLU","RoPE", "NeoX", ".."]
