[package]
name = "gip"
description = "The general inference program, a local LLM inference engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gip-gguf = { workspace = true }
half = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
gip-metal = { workspace = true }

[lints]
workspace = true
