/* embed.c turns a text file into a C source file that defines the file's
   contents as a null-terminated character array.  The build uses it to
   embed Metal kernel sources in the library.  */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum
{
  BYTES_PER_LINE = 12
};

/* Write a definition of the array NAME holding the bytes of INPUT_PATH
   to OUTPUT_PATH.  */
int
main (int argc, char **argv)
{
  if (argc != 4)
    {
      fprintf (stderr, "Usage: embed NAME INPUT OUTPUT\n");
      return EXIT_FAILURE;
    }
  const char *name = argv[1];
  const char *input_path = argv[2];
  const char *output_path = argv[3];

  FILE *input = fopen (input_path, "rb");
  if (input == NULL)
    {
      fprintf (stderr, "embed: %s: %s\n", input_path, strerror (errno));
      return EXIT_FAILURE;
    }
  FILE *output = fopen (output_path, "w");
  if (output == NULL)
    {
      fprintf (stderr, "embed: %s: %s\n", output_path, strerror (errno));
      fclose (input);
      return EXIT_FAILURE;
    }

  fprintf (output, "/* Generated by embed from %s.  */\n\n", input_path);
  fprintf (output, "const char %s[] = {\n", name);
  size_t count = 0;
  int c;
  while ((c = getc (input)) != EOF)
    {
      fprintf (output, "%s0x%02x,", count % BYTES_PER_LINE == 0 ? "  " : " ",
               (unsigned)c);
      count++;
      if (count % BYTES_PER_LINE == 0)
        fputc ('\n', output);
    }
  fprintf (output, "%s0x00\n};\n", count % BYTES_PER_LINE == 0 ? "  " : " ");

  int read_failed = ferror (input);
  fclose (input);
  if (read_failed)
    {
      fprintf (stderr, "embed: %s: read error\n", input_path);
      fclose (output);
      return EXIT_FAILURE;
    }
  if (ferror (output) || fclose (output) != 0)
    {
      fprintf (stderr, "embed: %s: %s\n", output_path, strerror (errno));
      return EXIT_FAILURE;
    }
  return EXIT_SUCCESS;
}
